<div class="container">

<table style="width: 100%;"><tr>
<td>ok</td>
<td style="text-align: right;">R Documentation</td>
</tr></table>
<h2>The unittest package's workhorse function</h2>

<h3>Description</h3>

<p>Report the test of an expression in TAP format.</p>


<h3>Usage</h3>

<pre><code class="language-R">  ok(test, description)
</code></pre>


<h3>Arguments</h3>

<table>
<tr style="vertical-align: top;">
<td><code>test</code></td>
<td>

<p>Expression to be tested. Evaluating to <code>TRUE</code> is treated as success,
anything else as failure.
</p>
</td>
</tr>
<tr style="vertical-align: top;">
<td><code>description</code></td>
<td>

<p>Character string describing the test. If a description is not given a 
character representation of the test expression will be used.
</p>
</td>
</tr>
</table>
<h3>Details</h3>

<p>See <code>unittest</code> package documentation.
</p>
<p>The <code>unittest.stop_on_fail</code> option tells unit test to stop on the first test failure.
This is useful when debugging long test scripts with multiple failures.
</p>
<p>The <code>unittest.output</code> option tells unittest where output should be sent.
This is most useful for vignettes, where sending output to
<code>stderr</code> separates the unittest output from the vignette itself.
</p>


<h3>Value</h3>

<p><code>ok()</code> returns whatever was returned when <code>test</code> is evaluated.
More importantly it has the side effect of printing the result of the
test in <code>TAP</code> format.
</p>


<h3>Examples</h3>

<pre><code class="language-R">

ok(1==1, "1 equals 1")

ok(1==1)

ok(1==2, "1 equals 2")

ok(all.equal(c(1,2),c(1,2)), "compare vectors")

fn &lt;- function () stop("oops")
ok(fn(), "something with a coding error")

ok(c("Some diagnostic", "messages"), "A failure with diagnostic messages")

## Write a failing unit test script
test_path &lt;- tempfile(fileext = ".R")
writeLines('
library(unittest)

ok(1==1)
ok(1==2)
ok(2==2)
ok(3==3)
', con = test_path)

# Without unittest.stop_on_fail, we see all failures:
options(unittest.stop_on_fail = NULL)
tryCatch(source(test_path), error = function (e) { print("=== error ===") })

# With, we stop at the first failing test:
options(unittest.stop_on_fail = TRUE)
tryCatch(source(test_path), error = function (e) { print("=== error ===") })
options(unittest.stop_on_fail = NULL)

## Send unittest output to stderr()
options(unittest.output = stderr())
ok(ut_cmp_equal(4, 5), "4 == 5? Probably not")

## Reset unittest output to default (stdout())
options(unittest.output = NULL)
ok(ut_cmp_equal(4, 5), "4 == 5? Probably not")


</code></pre>


</div>